import { Photo } from ".";

export const PHOTOS: Photo[] = [
  { id: "abbaye_de_murbach", title: "Abbaye de Murbach", url: "/img/2025-11/Abbaye_de_Murbach.jpg" },
  { id: "aiguille_du_midi_1", title: "Aiguille du Midi (1)", url: "/img/2025-11/Aiguille_du_Midi_1.jpg" },
  { id: "aiguille_du_midi_2", title: "Aiguille du Midi (2)", url: "/img/2025-11/Aiguille_du_Midi_2.jpg" },
  {
    id: "aiguille_du_midi_vs_mont-blanc_a_laube",
    title: "Aiguille du Midi Vs Mont-Blanc a laube",
    url: "/img/2025-11/Aiguille_du_Midi_Vs_Mont-Blanc_a_laube.jpg",
  },
  {
    id: "aiguille_du_midi_vs_mont-blanc",
    title: "Aiguille du Midi Vs Mont-Blanc",
    url: "/img/2025-11/Aiguille_du_Midi_Vs_Mont-Blanc.jpg",
  },
  { id: "arc-en-ciel_a_murbach", title: "Arc-en-ciel a Murbach", url: "/img/2025-11/Arc-en-ciel_a_Murbach.jpg" },
  { id: "aube_bernoise", title: "Aube Bernoise", url: "/img/2025-11/Aube_Bernoise.jpg" },
  {
    id: "aube_dautomne_au_hohneck",
    title: "Aube dautomne au Hohneck",
    url: "/img/2025-11/Aube_dautomne_au_Hohneck.jpg",
  },
  {
    id: "aube_dautomne_sur_la_route_des_vins",
    title: "Aube dautomne sur la Route des Vins",
    url: "/img/2025-11/Aube_dautomne_sur_la_Route_des_Vins.jpg",
  },
  {
    id: "aube_dete_au_grand_ballon",
    title: "Aube dete au Grand Ballon",
    url: "/img/2025-11/Aube_dete_au_Grand_Ballon.jpg",
  },
  {
    id: "aube_glaciale_au_grand_ballon",
    title: "Aube glaciale au Grand Ballon",
    url: "/img/2025-11/Aube_glaciale_au_Grand_Ballon.jpg",
  },
  { id: "aube_vosgienne", title: "Aube Vosgienne", url: "/img/2025-11/Aube_Vosgienne.jpg" },
  { id: "automne_au_cervin", title: "Automne au Cervin", url: "/img/2025-11/Automne_au_Cervin.jpg" },
  {
    id: "automne_au_haut-koenigsbourg",
    title: "Automne au Haut-Koenigsbourg",
    url: "/img/2025-11/Automne_au_Haut-Koenigsbourg.jpg",
  },
  {
    id: "automne_au_lac_de_pierre-percee",
    title: "Automne au lac de Pierre-Percee",
    url: "/img/2025-11/Automne_au_lac_de_Pierre-Percee.jpg",
  },
  {
    id: "cascades_vosgiennes_dautomne",
    title: "Cascades Vosgiennes dautomne",
    url: "/img/2025-11/Cascades_Vosgiennes_dautomne.jpg",
  },
  {
    id: "cascades_vosgiennes_de_laube_1",
    title: "Cascades Vosgiennes de laube (1)",
    url: "/img/2025-11/Cascades_Vosgiennes_de_laube_1.jpg",
  },
  {
    id: "cascades_vosgiennes_de_laube_2",
    title: "Cascades Vosgiennes de laube (2)",
    url: "/img/2025-11/Cascades_Vosgiennes_de_laube_2.jpg",
  },
  {
    id: "cascades_vosgiennes_de_laube_3",
    title: "Cascades Vosgiennes de laube (3)",
    url: "/img/2025-11/Cascades_Vosgiennes_de_laube_3.jpg",
  },
  { id: "cervin_matterhorn", title: "Cervin Matterhorn", url: "/img/2025-11/Cervin_Matterhorn.jpg" },
  { id: "champ_du_feu", title: "Champ du Feu", url: "/img/2025-11/Champ_du_Feu.jpg" },
  { id: "chateau_dandlau", title: "Chateau dAndlau", url: "/img/2025-11/Chateau_dAndlau.jpg" },
  {
    id: "cheminement_dautomne_sur_les_cretes",
    title: "Cheminement dautomne sur les cretes",
    url: "/img/2025-11/Cheminement_dautomne_sur_les_cretes.jpg",
  },
  {
    id: "cirque_glaciaire_du_hohneck_en_automne",
    title: "Cirque glaciaire du Hohneck en automne",
    url: "/img/2025-11/Cirque_glaciaire_du_Hohneck_en_automne.jpg",
  },
  { id: "coeur_vosgien", title: "Coeur Vosgien", url: "/img/2025-11/Coeur_Vosgien.jpg" },
  { id: "col_de_bussang", title: "Col de Bussang", url: "/img/2025-11/Col_de_Bussang.jpg" },
  {
    id: "communion_du_grand_ballon_avec_les_alpes_bernoises",
    title: "Communion du Grand Ballon avec les Alpes Bernoises",
    url: "/img/2025-11/Communion_du_Grand_Ballon_avec_les_Alpes_Bernoises.jpg",
  },
  { id: "couchant_a_lortenbourg", title: "Couchant a lOrtenbourg", url: "/img/2025-11/Couchant_a_lOrtenbourg.jpg" },
  { id: "couchant_a_thierenbach", title: "Couchant a Thierenbach", url: "/img/2025-11/Couchant_a_Thierenbach.jpg" },
  {
    id: "couchant_estival_sur_la_route_des_cretes",
    title: "Couchant estival sur la Route des Cretes",
    url: "/img/2025-11/Couchant_estival_sur_la_Route_des_Cretes.jpg",
  },
  {
    id: "echarpe_de_nuages_au_hohneck",
    title: "Echarpe de nuages au Hohneck",
    url: "/img/2025-11/Echarpe_de_nuages_au_Hohneck.jpg",
  },
  {
    id: "eclaircie_dans_le_sundgau",
    title: "Eclaircie dans le Sundgau",
    url: "/img/2025-11/Eclaircie_dans_le_Sundgau.jpg",
  },
  {
    id: "eclaircie_sur_la_route_des_vins",
    title: "Eclaircie sur la Route des Vins",
    url: "/img/2025-11/Eclaircie_sur_la_Route_des_Vins.jpg",
  },
  {
    id: "eclaircie_sur_la_vallee_noble",
    title: "Eclaircie sur la Vallee Noble",
    url: "/img/2025-11/Eclaircie_sur_la_Vallee_Noble.jpg",
  },
  { id: "envol_de_laube", title: "Envol de laube", url: "/img/2025-11/Envol_de_laube.jpg" },
  { id: "finale_15_euroairport", title: "Finale 15 EuroAirport", url: "/img/2025-11/Finale_15_EuroAirport.jpg" },
  {
    id: "givre_sur_le_haut-koenigsbourg",
    title: "Givre sur le Haut-Koenigsbourg",
    url: "/img/2025-11/Givre_sur_le_Haut-Koenigsbourg.jpg",
  },
  {
    id: "grand_ballon_vs_alpes_bernoises_1",
    title: "Grand Ballon Vs Alpes Bernoises (1)",
    url: "/img/2025-11/Grand_Ballon_Vs_Alpes_Bernoises_1.jpg",
  },
  {
    id: "grand_ballon_vs_alpes_bernoises_2",
    title: "Grand Ballon Vs Alpes Bernoises (2)",
    url: "/img/2025-11/Grand_Ballon_Vs_Alpes_Bernoises_2.jpg",
  },
  {
    id: "grand_ballon_vs_alpes_bernoises_3",
    title: "Grand Ballon Vs Alpes Bernoises (3)",
    url: "/img/2025-11/Grand_Ballon_Vs_Alpes_Bernoises_3.jpg",
  },
  { id: "grand_ballon_vs_bale", title: "Grand Ballon Vs Bale", url: "/img/2025-11/Grand_Ballon_Vs_Bale.jpg" },
  {
    id: "grand_ballon_vs_mont-blanc",
    title: "Grand Ballon Vs Mont-Blanc",
    url: "/img/2025-11/Grand_Ballon_Vs_Mont-Blanc.jpg",
  },
  {
    id: "haut-koenigsbourg_vs_alpes_bernoises",
    title: "Haut-Koenigsbourg Vs Alpes Bernoises",
    url: "/img/2025-11/Haut-Koenigsbourg_Vs_Alpes_Bernoises.jpg",
  },
  {
    id: "hiver_vs_automne_au_hohneck",
    title: "Hiver Vs Automne au Hohneck",
    url: "/img/2025-11/Hiver_Vs_Automne_au_Hohneck.jpg",
  },
  { id: "hohneck", title: "Hohneck", url: "/img/2025-11/Hohneck.jpg" },
  {
    id: "hohneck_vs_alpes_bernoises_1",
    title: "Hohneck Vs Alpes Bernoises (1)",
    url: "/img/2025-11/Hohneck_Vs_Alpes_Bernoises_1.jpg",
  },
  {
    id: "hohneck_vs_alpes_bernoises_2",
    title: "Hohneck Vs Alpes Bernoises (2)",
    url: "/img/2025-11/Hohneck_Vs_Alpes_Bernoises_2.jpg",
  },
  {
    id: "hohneck_vs_alpes_bernoises_3",
    title: "Hohneck Vs Alpes Bernoises (3)",
    url: "/img/2025-11/Hohneck_vs_Alpes_Bernoises_3.jpg",
  },
  { id: "hohneck_vs_bale", title: "Hohneck Vs Bale", url: "/img/2025-11/Hohneck_Vs_Bale.jpg" },
  { id: "hohneck_vs_grand_ballon", title: "Hohneck Vs Grand Ballon", url: "/img/2025-11/Hohneck_Vs_Grand_Ballon.jpg" },
  {
    id: "horizon_vosgien_dautomne_1",
    title: "Horizon Vosgien dautomne (1)",
    url: "/img/2025-11/Horizon_Vosgien_dautomne_1.jpg",
  },
  {
    id: "horizon_vosgien_dautomne_2",
    title: "Horizon Vosgien dautomne (2)",
    url: "/img/2025-11/Horizon_Vosgien_dautomne_2.jpg",
  },
  {
    id: "jungfraujoch_top_of_europe",
    title: "Jungfraujoch - Top of Europe",
    url: "/img/2025-11/Jungfraujoch_-_Top_of_Europe.jpg",
  },
  { id: "lac_blanc_congele", title: "Lac Blanc congele", url: "/img/2025-11/Lac_Blanc_congele.jpg" },
  { id: "lac_de_gerardmer", title: "Lac de Gerardmer", url: "/img/2025-11/Lac_de_Gerardmer.jpg" },
  { id: "lac_de_longemer_estival", title: "Lac de Longemer estival", url: "/img/2025-11/Lac_de_Longemer_estival.jpg" },
  {
    id: "lac_de_longemer_hivernal",
    title: "Lac de Longemer hivernal",
    url: "/img/2025-11/Lac_de_Longemer_hivernal.jpg",
  },
  {
    id: "lac_de_pierre-percee_estival",
    title: "Lac de Pierre-Percee estival",
    url: "/img/2025-11/Lac_de_Pierre-Percee_estival.jpg",
  },
  {
    id: "lac_de_pierre-percee_hivernal",
    title: "Lac de Pierre-Percee hivernal",
    url: "/img/2025-11/Lac_de_Pierre-Percee_hivernal.jpg",
  },
  { id: "lac_de_roselend", title: "Lac de Roselend", url: "/img/2025-11/Lac_de_Roselend.jpg" },
  { id: "lac_des_corbeaux", title: "Lac des Corbeaux", url: "/img/2025-11/Lac_des_Corbeaux.jpg" },
  {
    id: "lac_des_perches_automnal",
    title: "Lac des Perches automnal",
    url: "/img/2025-11/Lac_des_Perches_automnal.jpg",
  },
  { id: "lac_du_ballon", title: "Lac du Ballon", url: "/img/2025-11/Lac_du_Ballon.jpg" },
  {
    id: "lautomne_au_chateau_du_haut-koenigsbourg",
    title: "Lautomne au Chateau du Haut-Koenigsbourg",
    url: "/img/2025-11/Lautomne_au_Chateau_du_Haut-Koenigsbourg.jpg",
  },
  {
    id: "le_galtz_benissant_colmar",
    title: "Le Galtz benissant Colmar",
    url: "/img/2025-11/Le_Galtz_benissant_Colmar.jpg",
  },
  {
    id: "le_monument_des_diables_bleus_sur_la_mer_de_nuages",
    title: "Le Monument des Diables Bleus sur la mer de nuages",
    url: "/img/2025-11/Le_Monument_des_Diables_Bleus_sur_la_mer_de_nuages.jpg",
  },
  { id: "lepopee_vosgienne", title: "Lepopee Vosgienne", url: "/img/2025-11/LEpopee_Vosgienne.jpg" },
  {
    id: "les_vosges_entre_automne_et_hiver",
    title: "Les Vosges entre automne et hiver",
    url: "/img/2025-11/Les_Vosges_entre_automne_et_hiver.jpg",
  },
  { id: "letoile_de_vauban_1", title: "LEtoile de Vauban (1)", url: "/img/2025-11/LEtoile_de_Vauban_1.jpg" },
  { id: "letoile_de_vauban_2", title: "LEtoile de Vauban (2)", url: "/img/2025-11/LEtoile_de_Vauban_2.jpg" },
  { id: "levant_au_kaiserstuhl", title: "Levant au Kaiserstuhl", url: "/img/2025-11/Levant_au_Kaiserstuhl.jpg" },
  { id: "levant_bernois", title: "Levant Bernois", url: "/img/2025-11/Levant_Bernois.jpg" },
  { id: "levant_dans_le_sundgau", title: "Levant dans le Sundgau", url: "/img/2025-11/Levant_dans_le_Sundgau.jpg" },
  {
    id: "levant_dautomne_a_hunawihr",
    title: "Levant dautomne a Hunawihr",
    url: "/img/2025-11/Levant_dautomne_a_Hunawihr.jpg",
  },
  {
    id: "levant_dhiver_au_hohneck",
    title: "Levant dhiver au Hohneck",
    url: "/img/2025-11/Levant_dhiver_au_Hohneck.jpg",
  },
  {
    id: "levant_dhiver_sur_les_cretes_vosgiennes",
    title: "Levant dhiver sur les cretes Vosgiennes",
    url: "/img/2025-11/Levant_dhiver_sur_les_cretes_Vosgiennes.jpg",
  },
  { id: "levant_explosif", title: "Levant explosif", url: "/img/2025-11/Levant_explosif.jpg" },
  {
    id: "levant_glacial_au_grand_ballon",
    title: "Levant glacial au Grand Ballon",
    url: "/img/2025-11/Levant_glacial_au_Grand_Ballon.jpg",
  },
  {
    id: "levant_sur_le_massif_du_mont-blanc",
    title: "Levant sur le Massif du Mont-Blanc",
    url: "/img/2025-11/Levant_sur_le_Massif_du_Mont-Blanc.jpg",
  },
  {
    id: "lile_mysterieuse_eschentzwiller",
    title: "L’Île Mystérieuse Eschentzwiller",
    url: "/img/2025-11/LIle_Mysterieuse_Eschentzwiller.jpg",
  },
  {
    id: "massif_du_mont-blanc",
    title: "Massif du Mont-Blanc",
    url: "/img/2025-11/Massif_du_Mont-Blanc.jpg",
  },
  {
    id: "mer_de_nuages_au_grand_ballon",
    title: "Mer de nuages au Grand Ballon",
    url: "/img/2025-11/Mer_de_nuages_au_Grand_Ballon.jpg",
  },
  {
    id: "mer_de_nuages_au_haut-koenigsbourg",
    title: "Mer de nuages au Haut-Kœnigsbourg",
    url: "/img/2025-11/Mer_de_nuages_au_Haut-Koenigsbourg.jpg",
  },
  {
    id: "mer_de_nuages_au_hohneck_1",
    title: "Mer de nuages au Hohneck 1",
    url: "/img/2025-11/Mer_de_nuages_au_Hohneck_1.jpg",
  },
  {
    id: "mer_de_nuages_au_hohneck_2",
    title: "Mer de nuages au Hohneck 2",
    url: "/img/2025-11/Mer_de_nuages_au_Hohneck_2.jpg",
  },
  {
    id: "mer_de_nuages_sur_les_chateaux_de_ribeauville",
    title: "Mer de nuages sur les châteaux de Ribeauvillé",
    url: "/img/2025-11/Mer_de_nuages_sur_les_chateaux_de_Ribeauville.jpg",
  },
  {
    id: "miracle_a_guebwiller",
    title: "Miracle à Guebwiller",
    url: "/img/2025-11/Miracle_a_Guebwiller.jpg",
  },
  {
    id: "miracle_dans_la_vallee_noble",
    title: "Miracle dans la Vallée Noble",
    url: "/img/2025-11/Miracle_dans_la_Vallee_Noble.jpg",
  },
  {
    id: "mix_des_saisons_sur_la_route_des_cretes",
    title: "Mix des saisons sur la Route des Crêtes",
    url: "/img/2025-11/Mix_des_saisons_sur_la_Route_des_Cretes.jpg",
  },
  {
    id: "mont_sainte-odile",
    title: "Mont Sainte-Odile",
    url: "/img/2025-11/Mont_Sainte-Odile.jpg",
  },
  {
    id: "mont_sainte-odile_vs_alpes_bernoises",
    title: "Mont Sainte-Odile vs Alpes Bernoises",
    url: "/img/2025-11/Mont_Sainte-Odile_Vs_Alpes_Bernoises.jpg",
  },
  {
    id: "niedermorschwihr",
    title: "Niedermorschwihr",
    url: "/img/2025-11/Niedermorschwihr.jpg",
  },
  {
    id: "notre-dame_de_dusenbach",
    title: "Notre-Dame de Dusenbach",
    url: "/img/2025-11/Notre-Dame_de_Dusenbach.jpg",
  },
  {
    id: "patrouille_dhiver",
    title: "Patrouille d’hiver",
    url: "/img/2025-11/Patrouille_dhiver.jpg",
  },
  {
    id: "piper_au_haut-koenigsbourg",
    title: "Piper au Haut-Kœnigsbourg",
    url: "/img/2025-11/Piper_au_Haut-Koenigsbourg.jpg",
  },
  {
    id: "piper_sur_la_route_des_vins",
    title: "Piper sur la Route des Vins",
    url: "/img/2025-11/Piper_sur_la_Route_des_Vins.jpg",
  },
  {
    id: "plateau_des_1000_etangs",
    title: "Plateau des 1000 Étangs",
    url: "/img/2025-11/Plateau_des_1000_Etangs.jpg",
  },
  {
    id: "pleine_lune_au_grand_ballon",
    title: "Pleine lune au Grand Ballon",
    url: "/img/2025-11/Pleine_lune_au_Grand_Ballon.jpg",
  },
  {
    id: "presquile_du_haut-koenisgbourg",
    title: "Presqu’île du Haut-Kœnigsbourg",
    url: "/img/2025-11/Presquile_du_Haut-Koenisgbourg.jpg",
  },
  {
    id: "processeur_vegetal",
    title: "Processeur végétal",
    url: "/img/2025-11/Processeur_vegetal.jpg",
  },
  {
    id: "rayons_de_laube_sur_la_vallee_de_guebwiller",
    title: "Rayons de l’aube sur la Vallée de Guebwiller",
    url: "/img/2025-11/Rayons_de_laube_sur_la_Vallee_de_Guebwiller.jpg",
  },
  {
    id: "route_des_cretes_1",
    title: "Route des Crêtes 1",
    url: "/img/2025-11/Route_des_Cretes_1.jpg",
  },
  {
    id: "route_des_cretes_2",
    title: "Route des Crêtes 2",
    url: "/img/2025-11/Route_des_Cretes_2.jpg",
  },
  {
    id: "temple_du_donon",
    title: "Temple du Donon",
    url: "/img/2025-11/Temple_du_Donon.jpg",
  },
  {
    id: "tissage_dautomne",
    title: "Tissage d’automne",
    url: "/img/2025-11/Tissage_dautomne.jpg",
  },
  {
    id: "tourbiere_de_lispach",
    title: "Tourbière de Lispach",
    url: "/img/2025-11/Tourbiere_de_Lispach.jpg",
  },
  {
    id: "vallee_de_saint-amarin",
    title: "Vallée de Saint-Amarin",
    url: "/img/2025-11/Vallee_de_Saint-Amarin.jpg",
  },
  {
    id: "vignoble_de_soultzmatt",
    title: "Vignoble de Soultzmatt",
    url: "/img/2025-11/Vignoble_de_Soultzmatt.jpg",
  },
  {
    id: "automne_bernois",
    title: "Automne Bernois",
    url: "/img/2025-11/Automne_Bernois.jpg",
  },
  {
    id: "cap_sur_le_cervin",
    title: "Cap sur le Cervin",
    url: "/img/2025-11/Cap_sur_le_Cervin.jpg",
  },
  {
    id: "cervin_congele",
    title: "Cervin congelé",
    url: "/img/2025-11/Cervin_congele.jpg",
  },
  {
    id: "couchant_dore_sur_la_route_des_vins",
    title: "Couchant doré sur la Route des Vins",
    url: "/img/2025-11/Couchant_dore_sur_la_Route_des_Vins.jpg",
  },
  {
    id: "eguisheim",
    title: "Eguisheim",
    url: "/img/2025-11/Eguisheim.jpg",
  },
  {
    id: "finale_15_euroairport_2",
    title: "Finale 15 EuroAirport 2",
    url: "/img/2025-11/Finale_15_EuroAirport_2.jpg",
  },
  {
    id: "levant_a_laiguille_du_midi",
    title: "Levant à l’Aiguille du Midi",
    url: "/img/2025-11/Levant_a_lAiguille_du_Midi.jpg",
  },
  {
    id: "lever_de_soleil_dans_le_ried",
    title: "Lever de soleil dans le Ried",
    url: "/img/2025-11/Lever_de_soleil_dans_le_Ried.jpg",
  },
  {
    id: "massif_du_mont-blanc",
    title: "Massif du Mont-Blanc",
    url: "/img/2025-11/Massif_du_Mont-Blanc.jpg",
  },
  {
    id: "miracle_au_christ_du_galtz",
    title: "Miracle au Christ du Galtz",
    url: "/img/2025-11/Miracle_au_Christ_du_Galtz.jpg",
  },
  {
    id: "route_des_cretes_printemps",
    title: "Route des Crêtes – printemps",
    url: "/img/2025-11/Route_des_cretes_printemps.jpg",
  },
];

export const PHOTOS_COUNT = PHOTOS.length;
