import { SelectMenuOption } from './types';

interface countriesType {
  'fr': SelectMenuOption[];
  'en': SelectMenuOption[];
  'de': SelectMenuOption[];
}
export const COUNTRIES: countriesType = {
  'fr': [
    { title: 'France', value: 'FR' },
    { title: 'Allemagne', value: 'DE' },
    { title: 'Autriche', value: 'AT' },
    { title: 'Belgique', value: 'BE' },
    { title: 'Bulgarie', value: 'BG' },
    { title: 'Chypre', value: 'CY' },
    { title: 'République tchèque', value: 'CZ' },
    { title: 'Danemark', value: 'DK' },
    { title: 'Estonie', value: 'EE' },
    { title: 'Grèce', value: 'GR' },
    { title: 'Espagne', value: 'ES' },
    { title: 'Finlande', value: 'FI' },
    { title: 'Croatie', value: 'HR' },
    { title: 'Hongrie', value: 'HU' },
    { title: 'Irlande', value: 'IE' },
    { title: 'Islande', value: 'IS' },
    { title: 'Italie', value: 'IT' },
    { title: 'Liechtenstein', value: 'LI' },
    { title: 'Lituanie', value: 'LT' },
    { title: 'Luxembourg', value: 'LU' },
    { title: 'Lettonie', value: 'LV' },
    { title: 'Malte', value: 'MT' },
    { title: 'Pays-Bas', value: 'NL' },
    { title: 'Norvège', value: 'NO' },
    { title: 'Pologne', value: 'PL' },
    { title: 'Portugal', value: 'PT' },
    { title: 'Roumanie', value: 'RO' },
    { title: 'Suède', value: 'SE' },
    { title: 'Slovénie', value: 'SI' },
    { title: 'Slovaquie', value: 'SK' },
    { title: 'Royaume-Uni', value: 'GB' },
  ],
  'en': [
    { title: 'France', value: 'FR' },
    { title: 'Germany', value: 'DE' },
    { title: 'Austria', value: 'AT' },
    { title: 'Belgium', value: 'BE' },
    { title: 'Bulgaria', value: 'BG' },
    { title: 'Cyprus', value: 'CY' },
    { title: 'Czech Republic', value: 'CZ' },
    { title: 'Denmark', value: 'DK' },
    { title: 'Estonia', value: 'EE' },
    { title: 'Greece', value: 'GR' },
    { title: 'Spain', value: 'ES' },
    { title: 'Finland', value: 'FI' },
    { title: 'Croatia', value: 'HR' },
    { title: 'Hungary', value: 'HU' },
    { title: 'Ireland', value: 'IE' },
    { title: 'Iceland', value: 'IS' },
    { title: 'Italy', value: 'IT' },
    { title: 'Liechtenstein', value: 'LI' },
    { title: 'Lithuania', value: 'LT' },
    { title: 'Luxembourg', value: 'LU' },
    { title: 'Latvia', value: 'LV' },
    { title: 'Malta', value: 'MT' },
    { title: 'Netherlands', value: 'NL' },
    { title: 'Norway', value: 'NO' },
    { title: 'Poland', value: 'PL' },
    { title: 'Portugal', value: 'PT' },
    { title: 'Romania', value: 'RO' },
    { title: 'Sweden', value: 'SE' },
    { title: 'Slovenia', value: 'SI' },
    { title: 'Slovakia', value: 'SK' },
    { title: 'United Kingdom', value: 'GB' },
  ],
  'de': [
    { title: 'Frankreich', value: 'FR' },
    { title: 'Deutschland', value: 'DE' },
    { title: 'Österreich', value: 'AT' },
    { title: 'Belgien', value: 'BE' },
    { title: 'Bulgarien', value: 'BG' },
    { title: 'Zypern', value: 'CY' },
    { title: 'Tschechische Republik', value: 'CZ' },
    { title: 'Dänemark', value: 'DK' },
    { title: 'Estland', value: 'EE' },
    { title: 'Griechenland', value: 'GR' },
    { title: 'Spanien', value: 'ES' },
    { title: 'Finnland', value: 'FI' },
    { title: 'Kroatien', value: 'HR' },
    { title: 'Ungarn', value: 'HU' },
    { title: 'Irland', value: 'IE' },
    { title: 'Island', value: 'IS' },
    { title: 'Italien', value: 'IT' },
    { title: 'Liechtenstein', value: 'LI' },
    { title: 'Litauen', value: 'LT' },
    { title: 'Luxemburg', value: 'LU' },
    { title: 'Lettland', value: 'LV' },
    { title: 'Malta', value: 'MT' },
    { title: 'Niederlande', value: 'NL' },
    { title: 'Norwegen', value: 'NO' },
    { title: 'Polen', value: 'PL' },
    { title: 'Portugal', value: 'PT' },
    { title: 'Rumänien', value: 'RO' },
    { title: 'Schweden', value: 'SE' },
    { title: 'Slowenien', value: 'SI' },
    { title: 'Slowakei', value: 'SK' },
    { title: 'Vereinigtes Königreich', value: 'GB' },
  ],
} as const;
